org: adamrheggleston
app: dbd-randomiser-app
service: dbd-randomiser

frameworkVersion: ">=1.1.0 <2.0.0"

package:
  individually: true
  exclude:
    - ./**/*

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "*"

functions:
  getKiller:
    handler: dist/getKiller.handler
    environment:
      NODE_ENV: production
    package:
      include:
        - dist/getKiller.js
    events:
      - http:
          method: get
          path: killer
  getSurvivor:
    handler: dist/getSurvivor.handler
    environment:
      NODE_ENV: production
    package:
      include:
        - dist/getSurvivor.js
    events:
      - http:
          path: survivor
          method: get


plugins:
  - serverless-domain-manager

custom:
  stage: ${opt:stage, self:provider.stage}
  domains:
    prod: api.arhe.io
    dev: dev-api.arhe.io

  customDomain:
    domainName: "${self:custom.domains.${self:custom.stage}}"
    certificateName: 'arhe.io'
    stage: ${self:provider.stage}
    createRoute53Record: true
    basePath: 'dbd-randomiser'
    endpointType: 'edge'
